export const LIST_GIFTCARDS_REQUEST = 'LIST_GIFTCARDS_REQUEST';
export const LIST_GIFTCARDS_SUCCESS = 'LIST_GIFTCARDS_SUCCESS';
export const LIST_GIFTCARDS_FAILURE = 'LIST_GIFTCARDS_FAILURE';
export const GIFT_CARD_CREATE_REQUEST = "GIFT_CARD_CREATE_REQUEST";
export const GIFT_CARD_CREATE_SUCCESS = "GIFT_CARD_CREATE_SUCCESS";
export const GIFT_CARD_CREATE_FAIL = "GIFT_CARD_CREATE_FAIL";

  